---
title: Lance Gutin
timezone: Eastern Time (US & Canada)
collections:
  posts:
    title: Posts
    output: true
  travel:
    title: Travel
    output: true
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: true
  writing:
    title: Writing
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: writing
  values:
    layout: article
- scope:
    path: ''
    type: travel
  values:
    layout: article
- scope:
    path: ''
    type: work
  values:
    layout: default
permalink: pretty
markdown: kramdown
analytics_id: UA-17044912-3
description: Designer
