---
title: Lance Gutin
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  writing:
    title: Writing
    output: true
    layout: article
defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/posts/:title/"
